- hosts: all
  sudo: yes
  tasks:
    - name: yum update
      yum: name=* state=latest

    - name: Install libselinux-python
      yum: name=libselinux-python state=present

    - replace: dest=/etc/yum.repos.d/{{item}} regexp="enabled *= *1" replace="enabled=0"
      with_items:
      - epel.repo
      - remi.repo

    - name: install by yum
      yum: name={{item}} state=latest
      with_items:
        - httpd
        - vim
